SYMBOL = "GOLD"
TRADING_MODE = "DEMO"
TIMEFRAME_NAME = "M15"
LOOP_SECONDS = 900

RISK_PERCENT = 0.5
DAILY_TARGET = 100.0
MAX_POSITIONS = 1

BUY_RSI_MIN = 48
BUY_RSI_MAX = 65
SELL_RSI_MIN = 35
SELL_RSI_MAX = 52

MIN_ATR = 3.0
MAX_ATR = 25.0
SL_ATR_MULTIPLIER = 1.5
TP_ATR_MULTIPLIER = 2.25

MAX_SPREAD = 1.00
MIN_EMA_GAP_ATR = 0.05

PARTIAL_CLOSE_ENABLED = True
PARTIAL_CLOSE_TRIGGER_R = 1.0
PARTIAL_CLOSE_PERCENT = 0.50
BREAK_EVEN_ENABLED = True
BREAK_EVEN_TRIGGER_R = 1.0
BREAK_EVEN_OFFSET_POINTS = 0
ATR_TRAILING_MULTIPLIER = 2.0
SMART_EXIT_ENABLED = True
TIME_EXIT_ENABLED = True
TIME_EXIT_MAX_HOURS = 24.0
TIME_EXIT_MINIMUM_PROFIT = 0.0
MIN_SIGNAL_SCORE = 60
ORDER_DEVIATION = 20

NEWS_FILTER_ENABLED = True
NEWS_BLACKOUT_FILE = "config/news_blackout.csv"
NEWS_MINUTES_BEFORE = 30
NEWS_MINUTES_AFTER = 30
NEWS_BLOCK_IMPACTS = {"HIGH"}

FOREX_FACTORY_ENABLED = True
FOREX_FACTORY_URLS = [
    "https://nfs.faireconomy.media/ff_calendar_thisweek.json",
]
FOREX_FACTORY_CURRENCIES = {"USD"}

SESSION_FILTER_ENABLED = True
SESSION_START_HOUR = 15
SESSION_END_HOUR = 1

LOSS_STREAK_GUARD_ENABLED = True
MAX_CONSECUTIVE_LOSSES = 2

TELEGRAM_COMMANDS_ENABLED = True
TELEGRAM_POLL_SECONDS = 1.0
TELEGRAM_DAILY_REPORT_ENABLED = True
TELEGRAM_DAILY_REPORT_HOUR = 8
TELEGRAM_DAILY_REPORT_MINUTE = 0

BOT_MAGIC = 20260704
PAUSE_FILE = "data/bot_paused.flag"
TELEGRAM_OFFSET_FILE = "data/telegram_update_offset.txt"
TELEGRAM_REPORT_FILE = "data/telegram_daily_report_sent.txt"
TRADE_JOURNAL_FILE = "data/trade_journal.csv"
OPTIMIZER_RESULTS_FILE = "data/optimizer_results.csv"
